name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4                 # pulls your repo
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - run: pip install -r requirements.txt
    - run: pytest                               # <- add tests later

  export-model:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: "3.11", cache: "pip" }
    - run: pip install -r requirements.txt
    - run: python ml/pipeline_supervised.py
    - uses: actions/upload-artifact@v4          # store tflite in CI
      with:
        name: tflite-model
        path: models/*.tflite
